site_name: Distillery Documents
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to light mode
      primary: deep-orange
      accent: light-blue 
    - scheme: default 
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode    
      primary: teal
      accent: lime

plugins:
  - social

extra:
  social:
    - icon: fontawesome/regular/newspaper
      link: https://YourSubstackName.substack.com/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Followfox_ai
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/distillery.dev/


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg


nav:
  - Quick Start: index.md
  - Parameters:
      - Parameters Overview: Parameters/parameters_overview.md
      - Negative Prompt: Parameters/negative_prompt/negative_prompt.md
      - Seed: Parameters/seed/seed.md
      - CFG: Parameters/cfg/cfg.md
      - Aspect Ratio: Parameters/aspect_ratio/aspect_ratio.md
      - Denoise Strength: Parameters/denoise/denoise.md
      - Model: Parameters/model/model.md
      - LoRAs: Parameters/lora/lora.md
      - Controlnet: Parameters/control/control.md
      - Image to Image: Parameters/img2img/img2img.md
      - Inpainting: Parameters/inpaint/inpaint.md
      - LLM Prompt Assistant: Parameters/llm/llm.md
      - IP Adapter: Parameters/adapt/adapt.md
      - Sharpen: Parameters/sharpen/sharpen.md
      - Sampler: Parameters/sampler/sampler.md
      - Raw Mode: Parameters/raw/raw.md
      - Upscale Method: Parameters/upscale_method/upscale_method.md
  - Distillery Workflows:
      - Commands Overview: Distillery Workflows/commands_overview.md
      - /Serve: Distillery Workflows/serve/serve.md
      - /Zoomout: Distillery Workflows/zoomout/zoomout.md
      - /Upscale: Distillery Workflows/upscale/upscale.md
      - /Checkmetadata: Distillery Workflows/checkmetadata/checkmetadata.md
      - /Command-infos: Distillery Workflows/command_infos/command_infos.md
      - /User-stats: Distillery Workflows/user_stats/user_stats.md
      - /Manage-lora: Distill/manage_loras.md
      - /Suggest: Distillery Workflows/suggest/suggest.md
      - /Makemask: Distillery Workflows/makemask/makemask.md
      - /Distill: Distill/distill_overview.md
  - LoRA Training (/Distill):
      - Overview: Distill/distill_overview.md
      - Distill Command: Distill/distill_command.md
      - Single Image Training: Distill/single_image.md
      - Manage LoRAs: Distill/manage_loras.md
      - Pricing: Distill/distill_pricing.md
  - Subscriptions: 
      - Subscriptions Overview: Subscriptions/subscriptions_overview.md
      - Early User Subscription: Subscriptions/early_user.md
      - Founder's Pass: Subscriptions/founder_pass.md