site_name: Distillery Documents
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to light mode
      primary: deep-orange
      accent: light-blue 
    - scheme: default 
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode    
      primary: teal
      accent: lime

plugins:
  - social

extra:
  social:
    - icon: fontawesome/regular/newspaper
      link: https://YourSubstackName.substack.com/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Followfox_ai
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/distillery.dev/


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Quick Start: index.md
  - Parameters:
      - Parameters Overview: Parameters/parameters_overview.md
      - Seed: Parameters/seed/seed.md
      - Negative Prompt: Parameters/negative_prompt/negative_prompt.md
      - CFG: Parameters/cfg/cfg.md
      - LoRAs: Parameters/lora/lora.md
  - Alternative Workflows:
      - Commands Overview: Alternative Workflows/commands_overview.md
  - Subscriptions: 
    - Subscriptions Overview: Subscriptions/subscriptions_overview.md
    - Early User Subscription: Subscriptions/early_user.md
    - Founder's Pass: Subscriptions/founder_pass.md