name: Sync to Distillery-dev/site

on:
  push:
    branches:
      - main  # assuming you're using the main branch, change if needed

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source repo
      uses: actions/checkout@v2

    - name: Push to destination repo
      run: |
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git remote add dest https://x-access-token:${{ secrets.REPO_SYNC_TOKEN }}@github.com/Distillery-dev/site.git
        git push dest main
